import { Hind_Siliguri, Tiro_Bangla } from "next/font/google";
import "./globals.css";

const tirobangla = Tiro_Bangla({
  weight: "400",
  variable: "--font-tirobangla",
  subsets: ["bengali"],
});

const hindshiliguri = Hind_Siliguri({
  weight: ['300', '400', '500', '600', '700'],
  variable: "--font-hind-shiliguri",
  subsets: ["bengali"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={hindshiliguri.className}>
      <body>{children}</body>
    </html>
  )
}